import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const details = [
  // ─── Simpson Strong-Tie (7 entries) ───────────────────────────────────────
  {
    name: "Joist Hanger Selection Guide",
    description: "Comprehensive guide for selecting and installing wood construction connectors for joist hanger applications.",
    manufacturer: "Simpson Strong-Tie",
    trade: "carpentry",
    csiDivision: "06",
    csiTitle: "Wood, Plastics, and Composites",
    detailType: "connection",
    format: "PDF",
    sourceUrl: "https://www.strongtie.com/resources/literature/wood-construction-connectors-702702",
    tags: ["structural", "connection", "residential", "commercial", "joist-hanger"],
    isFree: true,
    notes: null,
  },
  {
    name: "Holdown and Anchor Bolt Details",
    description: "Detailed specifications for holdown devices and anchor bolt connections used in seismic and lateral load applications.",
    manufacturer: "Simpson Strong-Tie",
    trade: "carpentry",
    csiDivision: "06",
    csiTitle: "Wood, Plastics, and Composites",
    detailType: "structural",
    format: "PDF",
    sourceUrl: "https://www.strongtie.com/resources/literature/holdowns-706706",
    tags: ["structural", "holdown", "anchor", "residential", "seismic"],
    isFree: true,
    notes: null,
  },
  {
    name: "Post Base and Cap Connection Details",
    description: "Installation details for post base and cap hardware used in post-frame and deck construction.",
    manufacturer: "Simpson Strong-Tie",
    trade: "carpentry",
    csiDivision: "06",
    csiTitle: "Wood, Plastics, and Composites",
    detailType: "connection",
    format: "PDF",
    sourceUrl: "https://www.strongtie.com/resources/literature/post-frame-hardware-711711",
    tags: ["structural", "connection", "post-base", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "Hurricane Tie and Strap Details",
    description: "Connection details for hurricane ties and straps that anchor roof framing to wall framing for wind uplift resistance.",
    manufacturer: "Simpson Strong-Tie",
    trade: "carpentry",
    csiDivision: "06",
    csiTitle: "Wood, Plastics, and Composites",
    detailType: "connection",
    format: "PDF",
    sourceUrl: "https://www.strongtie.com/resources/literature/hurricane-ties-710710",
    tags: ["structural", "hurricane-tie", "roof-to-wall", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "Deck Connector and Fastener Guide",
    description: "Complete guide for deck construction connectors and fasteners including ledger attachments and post bases.",
    manufacturer: "Simpson Strong-Tie",
    trade: "carpentry",
    csiDivision: "06",
    csiTitle: "Wood, Plastics, and Composites",
    detailType: "connection",
    format: "PDF",
    sourceUrl: "https://www.strongtie.com/resources/literature/deck-connectors-721721",
    tags: ["structural", "deck", "connection", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "Concrete Anchor Systems",
    description: "Technical details for anchoring systems used to attach structural elements to concrete substrates.",
    manufacturer: "Simpson Strong-Tie",
    trade: "concrete",
    csiDivision: "03",
    csiTitle: "Concrete",
    detailType: "structural",
    format: "PDF",
    sourceUrl: "https://www.strongtie.com/resources/literature/anchoring-systems-707707",
    tags: ["structural", "anchor", "concrete", "commercial"],
    isFree: true,
    notes: null,
  },
  {
    name: "Masonry Connector Details",
    description: "Connection details for masonry veneer ties and anchors used in brick and stone veneer wall systems.",
    manufacturer: "Simpson Strong-Tie",
    trade: "masonry",
    csiDivision: "04",
    csiTitle: "Masonry",
    detailType: "connection",
    format: "PDF",
    sourceUrl: "https://www.strongtie.com/resources/literature/masonry-connectors-703703",
    tags: ["structural", "masonry", "veneer-tie", "commercial"],
    isFree: true,
    notes: null,
  },

  // ─── GAF Roofing (6 entries) ───────────────────────────────────────────────
  {
    name: "Eave and Drip Edge Flashing Detail",
    description: "Installation details for eave flashing and drip edge at the low end of sloped roof systems.",
    manufacturer: "GAF",
    trade: "roofing",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "flashing",
    format: "PDF",
    sourceUrl: "https://www.gaf.com/en-us/for-professionals/resources/detail-drawings",
    tags: ["roofing", "flashing", "eave", "drip-edge", "residential"],
    isFree: true,
    notes: "Navigate to eave details section",
  },
  {
    name: "Valley Flashing Detail",
    description: "Flashing details for roof valley intersections where two roof planes meet.",
    manufacturer: "GAF",
    trade: "roofing",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "flashing",
    format: "PDF",
    sourceUrl: "https://www.gaf.com/en-us/for-professionals/resources/detail-drawings#valley",
    tags: ["roofing", "flashing", "valley", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "Ridge Vent Installation Detail",
    description: "Installation details for ridge vent products that provide continuous attic ventilation along the roof peak.",
    manufacturer: "GAF",
    trade: "roofing",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://www.gaf.com/en-us/for-professionals/resources/detail-drawings#ridge",
    tags: ["roofing", "ventilation", "ridge-vent", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "Roof Penetration Flashing Detail",
    description: "Flashing details for pipe boots, vents, and other roof penetrations to prevent water intrusion.",
    manufacturer: "GAF",
    trade: "roofing",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "flashing",
    format: "PDF",
    sourceUrl: "https://www.gaf.com/en-us/for-professionals/resources/detail-drawings#penetrations",
    tags: ["roofing", "flashing", "penetration", "pipe-boot", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "Wall-to-Roof Termination Detail",
    description: "Step flashing and counter flashing details at the transition between vertical wall surfaces and sloped roofs.",
    manufacturer: "GAF",
    trade: "roofing",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "flashing",
    format: "PDF",
    sourceUrl: "https://www.gaf.com/en-us/for-professionals/resources/detail-drawings#wall",
    tags: ["roofing", "flashing", "step-flashing", "wall-transition", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "Starter Strip Application Detail",
    description: "Installation details for starter strip shingles at eaves and rakes to ensure proper first-course alignment.",
    manufacturer: "GAF",
    trade: "roofing",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://www.gaf.com/en-us/for-professionals/resources/detail-drawings#starter",
    tags: ["roofing", "starter-strip", "residential"],
    isFree: true,
    notes: null,
  },

  // ─── ZIP System / Huber (5 entries) ───────────────────────────────────────
  {
    name: "ZIP System Wall Sheathing Assembly",
    description: "Complete wall sheathing assembly details for ZIP System panels used as integrated air and water barrier.",
    manufacturer: "Huber Engineered Woods",
    trade: "carpentry",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "assembly",
    format: "PDF",
    sourceUrl: "https://www.huberwood.com/zip-system/resources/installation-details#wall",
    tags: ["sheathing", "air-barrier", "water-barrier", "residential", "wall"],
    isFree: true,
    notes: null,
  },
  {
    name: "ZIP System Roof Sheathing Assembly",
    description: "Roof sheathing assembly details for ZIP System panels serving as integrated roof underlayment.",
    manufacturer: "Huber Engineered Woods",
    trade: "carpentry",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "assembly",
    format: "PDF",
    sourceUrl: "https://www.huberwood.com/zip-system/resources/installation-details#roof",
    tags: ["sheathing", "roof", "underlayment", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "ZIP System Stretch Tape Window Flashing",
    description: "Window rough opening flashing details using ZIP System stretch tape for a continuous air and water seal.",
    manufacturer: "Huber Engineered Woods",
    trade: "carpentry",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "flashing",
    format: "PDF",
    sourceUrl: "https://www.huberwood.com/zip-system/resources/installation-details#window",
    tags: ["flashing", "window", "rough-opening", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "ZIP System Liquid Flash Detail",
    description: "Flashing details using ZIP System liquid-applied membrane at penetrations and complex transitions.",
    manufacturer: "Huber Engineered Woods",
    trade: "carpentry",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "flashing",
    format: "PDF",
    sourceUrl: "https://www.huberwood.com/zip-system/resources/installation-details#liquid-flash",
    tags: ["flashing", "liquid-flash", "penetration", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "ZIP R-Sheathing Insulated Panel Assembly",
    description: "Insulated wall assembly details using ZIP R-Sheathing panels to provide continuous exterior insulation.",
    manufacturer: "Huber Engineered Woods",
    trade: "insulation",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "assembly",
    format: "PDF",
    sourceUrl: "https://www.huberwood.com/zip-system/resources/installation-details#zip-r",
    tags: ["insulation", "continuous-insulation", "wall", "residential", "energy-code"],
    isFree: true,
    notes: null,
  },

  // ─── James Hardie (4 entries) ─────────────────────────────────────────────
  {
    name: "HardiePlank Lap Siding Installation",
    description: "Installation guide for HardiePlank fiber cement lap siding including fastening, spacing, and clearance requirements.",
    manufacturer: "James Hardie",
    trade: "carpentry",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://www.jameshardie.com/technical-information/installation-guides",
    tags: ["siding", "fiber-cement", "lap-siding", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "HardieTrim and Fascia Details",
    description: "Installation details for HardieTrim boards and fascia used as exterior trim and finish elements.",
    manufacturer: "James Hardie",
    trade: "carpentry",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://www.jameshardie.com/technical-information/installation-guides#trim",
    tags: ["siding", "trim", "fascia", "fiber-cement", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "Hardie Siding Window and Door Flashing",
    description: "Flashing details at window and door openings in fiber cement siding systems to prevent water infiltration.",
    manufacturer: "James Hardie",
    trade: "carpentry",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "flashing",
    format: "PDF",
    sourceUrl: "https://www.jameshardie.com/technical-information/installation-guides#flashing",
    tags: ["siding", "flashing", "window", "door", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "HardiePanel Vertical Siding Installation",
    description: "Installation guide for HardiePanel vertical fiber cement siding panels and joint treatment.",
    manufacturer: "James Hardie",
    trade: "carpentry",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://www.jameshardie.com/technical-information/installation-guides#panel",
    tags: ["siding", "fiber-cement", "vertical", "panel", "residential"],
    isFree: true,
    notes: null,
  },

  // ─── ARCAT (8 entries) ────────────────────────────────────────────────────
  {
    name: "Foundation Waterproofing Details",
    description: "CAD details for below-grade foundation waterproofing systems including drainage board and membrane applications.",
    manufacturer: "ARCAT",
    trade: "concrete",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "waterproofing",
    format: "DWG",
    sourceUrl: "https://www.arcat.com/arcatcos/cos33/arc33702.html",
    tags: ["waterproofing", "foundation", "below-grade", "residential", "commercial"],
    isFree: true,
    notes: "Free registration required",
  },
  {
    name: "Exterior Wall Assembly Sections",
    description: "CAD cross-section details for exterior wall assemblies showing framing, sheathing, insulation, and cladding layers.",
    manufacturer: "ARCAT",
    trade: "carpentry",
    csiDivision: "06",
    csiTitle: "Wood, Plastics, and Composites",
    detailType: "assembly",
    format: "DWG",
    sourceUrl: "https://www.arcat.com/arcatcos/cos33/arc33061.html",
    tags: ["wall", "assembly", "cross-section", "residential", "commercial"],
    isFree: true,
    notes: "Free registration required",
  },
  {
    name: "Concrete Slab-on-Grade Details",
    description: "CAD details for concrete slab-on-grade construction including vapor barrier, reinforcement, and edge conditions.",
    manufacturer: "ARCAT",
    trade: "concrete",
    csiDivision: "03",
    csiTitle: "Concrete",
    detailType: "assembly",
    format: "DWG",
    sourceUrl: "https://www.arcat.com/arcatcos/cos33/arc33031.html",
    tags: ["concrete", "slab", "foundation", "vapor-barrier", "residential"],
    isFree: true,
    notes: "Free registration required",
  },
  {
    name: "Interior Partition Wall Details",
    description: "CAD details for interior non-load-bearing partition wall framing and drywall assembly.",
    manufacturer: "ARCAT",
    trade: "drywall",
    csiDivision: "09",
    csiTitle: "Finishes",
    detailType: "assembly",
    format: "DWG",
    sourceUrl: "https://www.arcat.com/arcatcos/cos33/arc33092.html",
    tags: ["partition", "drywall", "framing", "interior", "commercial"],
    isFree: true,
    notes: "Free registration required",
  },
  {
    name: "Suspended Ceiling Grid Details",
    description: "CAD details for suspended acoustical ceiling tile grid systems including hanger wire and perimeter conditions.",
    manufacturer: "ARCAT",
    trade: "drywall",
    csiDivision: "09",
    csiTitle: "Finishes",
    detailType: "assembly",
    format: "DWG",
    sourceUrl: "https://www.arcat.com/arcatcos/cos33/arc33095.html",
    tags: ["ceiling", "ACT", "suspended", "commercial"],
    isFree: true,
    notes: "Free registration required",
  },
  {
    name: "Door Frame and Hardware Details",
    description: "CAD details for door frame installation, rough opening dimensions, and hardware placement for residential and commercial doors.",
    manufacturer: "ARCAT",
    trade: "carpentry",
    csiDivision: "08",
    csiTitle: "Openings",
    detailType: "installation",
    format: "DWG",
    sourceUrl: "https://www.arcat.com/arcatcos/cos33/arc33081.html",
    tags: ["door", "frame", "hardware", "commercial", "residential"],
    isFree: true,
    notes: "Free registration required",
  },
  {
    name: "Storefront Glazing System Details",
    description: "CAD details for aluminum storefront glazing systems including frame profiles, anchoring, and sill conditions.",
    manufacturer: "ARCAT",
    trade: "glazing",
    csiDivision: "08",
    csiTitle: "Openings",
    detailType: "assembly",
    format: "DWG",
    sourceUrl: "https://www.arcat.com/arcatcos/cos33/arc33084.html",
    tags: ["glazing", "storefront", "aluminum", "commercial"],
    isFree: true,
    notes: "Free registration required",
  },
  {
    name: "Tile Floor and Wall Installation Details",
    description: "CAD details for ceramic and porcelain tile installation on floors and walls including substrate preparation and waterproofing.",
    manufacturer: "ARCAT",
    trade: "flooring",
    csiDivision: "09",
    csiTitle: "Finishes",
    detailType: "installation",
    format: "DWG",
    sourceUrl: "https://www.arcat.com/arcatcos/cos33/arc33093.html",
    tags: ["tile", "flooring", "waterproofing", "residential", "commercial"],
    isFree: true,
    notes: "Free registration required",
  },

  // ─── CADdetails.com (6 entries) ───────────────────────────────────────────
  {
    name: "Metal Roof Panel Details",
    description: "CAD details for standing seam and metal roof panel systems including clips, fasteners, and ridge conditions.",
    manufacturer: "CADdetails",
    trade: "roofing",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "DWG",
    sourceUrl: "https://www.caddetails.com/categories/metal-roofing",
    tags: ["roofing", "metal", "standing-seam", "commercial"],
    isFree: true,
    notes: "Free registration required",
  },
  {
    name: "EIFS/Stucco Wall System Details",
    description: "CAD details for Exterior Insulation and Finish System (EIFS) and stucco wall assemblies.",
    manufacturer: "CADdetails",
    trade: "painting",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "assembly",
    format: "DWG",
    sourceUrl: "https://www.caddetails.com/categories/eifs",
    tags: ["EIFS", "stucco", "exterior", "commercial"],
    isFree: true,
    notes: "Free registration required",
  },
  {
    name: "Waterproofing Membrane Details",
    description: "CAD details for sheet-applied and fluid-applied waterproofing membrane systems for below-grade and plaza deck applications.",
    manufacturer: "CADdetails",
    trade: "concrete",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "waterproofing",
    format: "DWG",
    sourceUrl: "https://www.caddetails.com/categories/waterproofing",
    tags: ["waterproofing", "membrane", "below-grade", "commercial"],
    isFree: true,
    notes: "Free registration required",
  },
  {
    name: "Fire-Rated Penetration Seal Details",
    description: "CAD details for firestopping and fire-rated penetration seals at pipe, conduit, and duct penetrations through rated assemblies.",
    manufacturer: "CADdetails",
    trade: "fire_protection",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "DWG",
    sourceUrl: "https://www.caddetails.com/categories/firestopping",
    tags: ["firestop", "fire-rated", "penetration", "commercial"],
    isFree: true,
    notes: "Free registration required",
  },
  {
    name: "Expansion Joint and Sealant Details",
    description: "CAD details for building expansion joints and sealant conditions at structural movement locations.",
    manufacturer: "CADdetails",
    trade: "general_labor",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "DWG",
    sourceUrl: "https://www.caddetails.com/categories/expansion-joints",
    tags: ["expansion-joint", "sealant", "commercial"],
    isFree: true,
    notes: "Free registration required",
  },
  {
    name: "Insulated Metal Panel Wall Details",
    description: "CAD details for insulated metal panel wall systems used in commercial and industrial building envelopes.",
    manufacturer: "CADdetails",
    trade: "insulation",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "assembly",
    format: "DWG",
    sourceUrl: "https://www.caddetails.com/categories/insulated-metal-panels",
    tags: ["insulated-panel", "metal", "wall", "commercial"],
    isFree: true,
    notes: "Free registration required",
  },

  // ─── Building America Solution Center (5 entries) ─────────────────────────
  {
    name: "Climate Zone 3B Wall Assembly (Dry)",
    description: "US DOE wall assembly recommendations and details optimized for hot-dry Climate Zone 3B as found in Nevada.",
    manufacturer: "Building America Solution Center",
    trade: "insulation",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "assembly",
    format: "PDF",
    sourceUrl: "https://basc.pnnl.gov/resource-guides/wall-insulation",
    tags: ["wall", "insulation", "climate-zone-3B", "energy-code", "residential", "nevada"],
    isFree: true,
    notes: "US DOE resource — select climate zone 3B for Nevada",
  },
  {
    name: "Attic Insulation and Air Sealing Guide",
    description: "US DOE resource guide for attic insulation installation and air sealing best practices.",
    manufacturer: "Building America Solution Center",
    trade: "insulation",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "assembly",
    format: "PDF",
    sourceUrl: "https://basc.pnnl.gov/resource-guides/attic-insulation",
    tags: ["insulation", "attic", "air-sealing", "energy-code", "residential"],
    isFree: true,
    notes: "US DOE resource",
  },
  {
    name: "Foundation Insulation Details",
    description: "US DOE details for foundation insulation including slab edge, crawlspace, and basement configurations.",
    manufacturer: "Building America Solution Center",
    trade: "insulation",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "assembly",
    format: "PDF",
    sourceUrl: "https://basc.pnnl.gov/resource-guides/foundation-insulation",
    tags: ["insulation", "foundation", "slab-edge", "crawlspace", "energy-code", "residential"],
    isFree: true,
    notes: "US DOE resource",
  },
  {
    name: "Window and Door Installation Best Practices",
    description: "US DOE resource guide for window and door installation with flashing and air sealing details.",
    manufacturer: "Building America Solution Center",
    trade: "carpentry",
    csiDivision: "08",
    csiTitle: "Openings",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://basc.pnnl.gov/resource-guides/window-installation",
    tags: ["window", "door", "flashing", "air-sealing", "residential"],
    isFree: true,
    notes: "US DOE resource",
  },
  {
    name: "Duct Sealing and Insulation Details",
    description: "US DOE resource guide for HVAC duct sealing and insulation to meet energy code requirements.",
    manufacturer: "Building America Solution Center",
    trade: "hvac",
    csiDivision: "23",
    csiTitle: "HVAC",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://basc.pnnl.gov/resource-guides/ducts",
    tags: ["hvac", "duct", "sealing", "insulation", "energy-code", "residential"],
    isFree: true,
    notes: "US DOE resource",
  },

  // ─── Owens Corning (4 entries) ────────────────────────────────────────────
  {
    name: "Duration Shingle Installation Guide",
    description: "Installation guide for Owens Corning Duration architectural shingles including nailing patterns and starter course.",
    manufacturer: "Owens Corning",
    trade: "roofing",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://www.owenscorning.com/en-us/roofing/shingles/duration",
    tags: ["roofing", "shingle", "installation", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "Batt Insulation Installation Details",
    description: "Installation details for fiberglass batt insulation in wall, floor, and ceiling cavities.",
    manufacturer: "Owens Corning",
    trade: "insulation",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://www.owenscorning.com/en-us/insulation/residential",
    tags: ["insulation", "batt", "fiberglass", "wall", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "Blown-In Insulation Application Details",
    description: "Application guide for blown-in loose-fill insulation in attics and enclosed cavities.",
    manufacturer: "Owens Corning",
    trade: "insulation",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://www.owenscorning.com/en-us/insulation/residential/blown-in",
    tags: ["insulation", "blown-in", "attic", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "Rigid Foam Board Insulation Details",
    description: "Installation details for XPS rigid foam board insulation used as continuous exterior insulation and below-grade applications.",
    manufacturer: "Owens Corning",
    trade: "insulation",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://www.owenscorning.com/en-us/insulation/commercial/rigid-foam",
    tags: ["insulation", "rigid-foam", "XPS", "continuous-insulation", "below-grade"],
    isFree: true,
    notes: null,
  },

  // ─── LP Building Solutions (3 entries) ────────────────────────────────────
  {
    name: "LP SmartSide Lap Siding Installation",
    description: "Installation guide for LP SmartSide engineered wood lap siding including fastening and clearance requirements.",
    manufacturer: "LP Building Solutions",
    trade: "carpentry",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://lpcorp.com/resources/installation-guides/smartside-lap-siding",
    tags: ["siding", "engineered-wood", "lap-siding", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "LP SmartSide Trim Installation",
    description: "Installation guide for LP SmartSide engineered wood trim, fascia, and soffit products.",
    manufacturer: "LP Building Solutions",
    trade: "carpentry",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://lpcorp.com/resources/installation-guides/smartside-trim",
    tags: ["siding", "trim", "fascia", "engineered-wood", "residential"],
    isFree: true,
    notes: null,
  },
  {
    name: "LP TechShield Radiant Barrier Sheathing",
    description: "Installation guide for LP TechShield radiant barrier roof sheathing to reduce attic heat gain in hot climates.",
    manufacturer: "LP Building Solutions",
    trade: "carpentry",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://lpcorp.com/resources/installation-guides/techshield",
    tags: ["sheathing", "radiant-barrier", "roof", "energy-code", "residential"],
    isFree: true,
    notes: "Relevant for Nevada's hot climate",
  },

  // ─── Government / Code Body Resources (5 entries) ─────────────────────────
  {
    name: "WBDG Wall Section Details",
    description: "US government building envelope design guide for wall systems including sections and assembly recommendations.",
    manufacturer: "WBDG / NIBS",
    trade: "carpentry",
    csiDivision: "06",
    csiTitle: "Wood, Plastics, and Composites",
    detailType: "assembly",
    format: "PDF",
    sourceUrl: "https://www.wbdg.org/guides-specifications/building-envelope-design-guide/wall-systems",
    tags: ["wall", "assembly", "government", "commercial", "residential"],
    isFree: true,
    notes: "US government resource — National Institute of Building Sciences",
  },
  {
    name: "WBDG Roofing Systems Guide",
    description: "US government building envelope design guide covering low-slope and steep-slope roofing system design.",
    manufacturer: "WBDG / NIBS",
    trade: "roofing",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "assembly",
    format: "PDF",
    sourceUrl: "https://www.wbdg.org/guides-specifications/building-envelope-design-guide/roofing-systems",
    tags: ["roofing", "low-slope", "steep-slope", "government", "commercial"],
    isFree: true,
    notes: "US government resource — National Institute of Building Sciences",
  },
  {
    name: "WBDG Below-Grade Waterproofing Guide",
    description: "US government design guide for below-grade waterproofing systems including material selection and application details.",
    manufacturer: "WBDG / NIBS",
    trade: "concrete",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "waterproofing",
    format: "PDF",
    sourceUrl: "https://www.wbdg.org/guides-specifications/building-envelope-design-guide/below-grade-waterproofing",
    tags: ["waterproofing", "foundation", "below-grade", "government", "commercial"],
    isFree: true,
    notes: "US government resource — National Institute of Building Sciences",
  },
  {
    name: "FEMA Coastal Construction Wind-Resistant Details",
    description: "FEMA P-499 publication with structural details for wind-resistant construction in high-wind and coastal zones.",
    manufacturer: "FEMA",
    trade: "carpentry",
    csiDivision: "06",
    csiTitle: "Wood, Plastics, and Composites",
    detailType: "structural",
    format: "PDF",
    sourceUrl: "https://www.fema.gov/emergency-managers/risk-management/building-science/publications",
    tags: ["structural", "wind-resistant", "high-wind", "government", "residential"],
    isFree: true,
    notes: "Search for FEMA P-499",
  },
  {
    name: "ENERGY STAR Air Sealing Guide",
    description: "EPA/ENERGY STAR thermal bypass checklist and air sealing guide for residential new construction.",
    manufacturer: "ENERGY STAR / EPA",
    trade: "insulation",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "assembly",
    format: "PDF",
    sourceUrl: "https://www.energystar.gov/partner_resources/residential_new/homes_prog_reqs/thermal_bypass",
    tags: ["air-sealing", "thermal-bypass", "energy-code", "residential", "government"],
    isFree: true,
    notes: "EPA/ENERGY STAR resource",
  },

  // ─── CertainTeed (2 entries) ──────────────────────────────────────────────
  {
    name: "CertainTeed Gypsum Board Installation",
    description: "Installation guide for CertainTeed gypsum board and fire-rated drywall assemblies.",
    manufacturer: "CertainTeed",
    trade: "drywall",
    csiDivision: "09",
    csiTitle: "Finishes",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://www.certainteed.com/resources/gypsum-installation",
    tags: ["drywall", "gypsum", "fire-rated", "residential", "commercial"],
    isFree: true,
    notes: null,
  },
  {
    name: "CertainTeed Vinyl Siding Installation",
    description: "Installation guide for CertainTeed vinyl siding including panel hanging, trim, and accessory details.",
    manufacturer: "CertainTeed",
    trade: "carpentry",
    csiDivision: "07",
    csiTitle: "Thermal and Moisture Protection",
    detailType: "installation",
    format: "PDF",
    sourceUrl: "https://www.certainteed.com/resources/siding-installation",
    tags: ["siding", "vinyl", "residential"],
    isFree: true,
    notes: null,
  },

  // ─── Pella (1 entry) ──────────────────────────────────────────────────────
  {
    name: "Pella Window Installation Details",
    description: "CAD installation details for Pella windows including flashing, rough opening, and sill pan configurations.",
    manufacturer: "Pella",
    trade: "carpentry",
    csiDivision: "08",
    csiTitle: "Openings",
    detailType: "installation",
    format: "DWG",
    sourceUrl: "https://www.pella.com/professionals/resources/installation-details/",
    tags: ["window", "installation", "flashing", "rough-opening", "residential"],
    isFree: true,
    notes: null,
  },

  // ─── Andersen (1 entry) ───────────────────────────────────────────────────
  {
    name: "Andersen Window Flashing Details",
    description: "Flashing detail drawings for Andersen windows including pan flashing and head flashing conditions.",
    manufacturer: "Andersen",
    trade: "carpentry",
    csiDivision: "08",
    csiTitle: "Openings",
    detailType: "flashing",
    format: "PDF",
    sourceUrl: "https://www.andersenwindows.com/for-professionals/detail-drawings/",
    tags: ["window", "flashing", "pan-flashing", "residential"],
    isFree: true,
    notes: null,
  },
];

async function main() {
  let created = 0;
  let updated = 0;

  for (const detail of details) {
    const result = await prisma.detailLibraryItem.upsert({
      where: { sourceUrl: detail.sourceUrl },
      update: {
        name: detail.name,
        description: detail.description,
        manufacturer: detail.manufacturer,
        trade: detail.trade,
        csiDivision: detail.csiDivision,
        csiTitle: detail.csiTitle,
        detailType: detail.detailType,
        format: detail.format,
        tags: detail.tags,
        isFree: detail.isFree,
        notes: detail.notes,
      },
      create: detail,
    });

    if (result.createdAt.getTime() === result.updatedAt.getTime()) {
      created++;
    } else {
      updated++;
    }
  }

  console.log(`Detail library seeded: ${created} created, ${updated} updated (${details.length} total)`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
