import { PlansetExtraction } from "../types";

export const zkhoExtraction: PlansetExtraction = {
  project: {
    name: "Kalter Creek Residence",
    shortCode: "ZKHO",
    address: "630 Woodridge Circle",
    city: "Incline Village",
    state: "NV",
    zip: "89451",
    projectType: "Residential Remodel",
    ownerFirstName: "Zachary",
    ownerLastName: "Kalter",
    ownerAddress: "15302 Central Ave, Chino, CA 91710",
    architect: "Elise Fett & Associates, Ltd.",
    engineer: "Palisade Engineering — Joel Heidema",
    interiorDesigner: "Some September Studio",
    existingSqft: 3934,
    addedSqft: 359,
    constructionType: "remodel",
    bedrooms: 5,
    bathrooms: 6,
    specialRequirements: [
      "TRPA compliance required",
      "Defensible space (IWUI zones)",
      "Dark sky exterior lighting",
      "BMP implementation (infiltration trenches, drywells)",
      "NLTPD fire requirements",
      "Washoe County engineering notes",
    ],
    hazardNotes:
      "Mountain construction — snow load, wildfire zone, TRPA jurisdiction. BMPs required for Lake Tahoe Basin.",
    nearestER: "Incline Village Community Hospital",
    nearestERAddress: "880 Alder Ave, Incline Village, NV 89451",
  },

  quote: {
    title: "Kalter Creek Residence — Full Interior Remodel",
    scopeText:
      "Complete interior remodel of existing 3,934 SF residence with 359 SF addition (flex room). Scope includes: demolition of interior walls and fixtures on both levels; new framing, plumbing rough-in for 6 full bathrooms, full electrical rewire, HVAC duct extensions, insulation upgrades, drywall/plaster, tile/stone (including all-stone fireplace), custom casework throughout, reclaimed wood wall/ceiling cladding, custom metalwork, flooring, painting, new decking with hot tub and gas firepit, window/door replacement, and TRPA-compliant site work including BMPs and defensible space clearing. 5 bedrooms, 6 full baths, kitchen remodel, wine room, flex room, theater/den.",
    estimatedDuration: "26 weeks",
    materialMarkupPct: 20,
    overheadPct: 15,
    profitPct: 12,
  },

  trades: [
    // 1. Demolition
    {
      trade: "demolition",
      sectionTitle: "Demolition",
      lineItems: [
        {
          description:
            "Interior wall demolition — upper level (kitchen, dining, living room, bath 2, master bath, WIC walls per A-2 demo plan)",
          quantity: 1,
          unit: "LS",
          unitPrice: 12000,
          vendorCost: 8000,
          isMaterial: false,
          sourceSheet: "A-2",
        },
        {
          description:
            "Interior wall demolition — lower level (bath 1 reconfig, storage walls, crawl space prep per A-1 demo plan)",
          quantity: 1,
          unit: "LS",
          unitPrice: 8000,
          vendorCost: 5500,
          isMaterial: false,
          sourceSheet: "A-1",
        },
        {
          description:
            "Fixture removal — existing bathroom fixtures (toilets, vanities, tubs, showers) — 4 bathrooms being remodeled",
          quantity: 4,
          unit: "EA",
          unitPrice: 1200,
          vendorCost: 800,
          isMaterial: false,
          sourceSheet: "A-1, A-2",
        },
        {
          description:
            "Kitchen demolition — existing cabinets, countertops, appliances, backsplash",
          quantity: 1,
          unit: "LS",
          unitPrice: 5000,
          vendorCost: 3500,
          isMaterial: false,
          sourceSheet: "A-2",
        },
        {
          description: "Flooring removal — existing flooring in remodeled areas",
          quantity: 2800,
          unit: "SF",
          unitPrice: 3,
          vendorCost: 2,
          isMaterial: false,
          sourceSheet: "A-7, A-8",
        },
        {
          description: "Existing W/D area demo for Bath 5 conversion",
          quantity: 1,
          unit: "LS",
          unitPrice: 2500,
          vendorCost: 1800,
          isMaterial: false,
          sourceSheet: "A-2",
        },
        {
          description:
            "Deck demolition — portions of existing deck for new configuration",
          quantity: 180,
          unit: "SF",
          unitPrice: 12,
          vendorCost: 8,
          isMaterial: false,
          sourceSheet: "SP-2",
        },
        {
          description:
            "Debris haul-off and disposal (estimated 4 roll-off loads)",
          quantity: 4,
          unit: "EA",
          unitPrice: 1800,
          vendorCost: 1200,
          isMaterial: false,
          sourceSheet: "SP-1",
        },
      ],
    },

    // 2. Concrete & Foundation
    {
      trade: "concrete",
      sectionTitle: "Concrete & Foundation",
      lineItems: [
        {
          description: "New slab on grade — flex room (per A-3, section detail)",
          quantity: 320,
          unit: "SF",
          unitPrice: 18,
          vendorCost: 12,
          isMaterial: false,
          sourceSheet: "A-3",
        },
        {
          description:
            "Stepped stem walls — flex room foundation (per A-1 detail 2)",
          quantity: 80,
          unit: "LF",
          unitPrice: 95,
          vendorCost: 65,
          isMaterial: false,
          sourceSheet: "A-1",
        },
        {
          description:
            "Sub-slab insulation — R-10 rigid foam below flex room slab",
          quantity: 320,
          unit: "SF",
          unitPrice: 4,
          vendorCost: 2.5,
          isMaterial: true,
          sourceSheet: "A-3",
        },
        {
          description:
            "Infiltration trenches — BMP treatments A through G per SP-4",
          quantity: 7,
          unit: "EA",
          unitPrice: 3500,
          vendorCost: 2400,
          isMaterial: false,
          sourceSheet: "SP-4",
        },
        {
          description: "Prefabricated drywell installations per SP-4",
          quantity: 3,
          unit: "EA",
          unitPrice: 2800,
          vendorCost: 1900,
          isMaterial: false,
          sourceSheet: "SP-4",
        },
      ],
    },

    // 3. Framing
    {
      trade: "carpentry",
      sectionTitle: "Framing",
      lineItems: [
        {
          description:
            "New 2x6 exterior/separation walls — lower level (hall, flex room, wine storage per A-3)",
          quantity: 160,
          unit: "LF",
          unitPrice: 32,
          vendorCost: 22,
          isMaterial: false,
          sourceSheet: "A-3",
        },
        {
          description:
            "New 2x4 interior partition walls — lower level (bath 2, closets per A-3)",
          quantity: 120,
          unit: "LF",
          unitPrice: 24,
          vendorCost: 16,
          isMaterial: false,
          sourceSheet: "A-3",
        },
        {
          description:
            "New 2x6 walls — upper level (kitchen, bath 5, WIC, bedroom reconfig per A-4)",
          quantity: 200,
          unit: "LF",
          unitPrice: 32,
          vendorCost: 22,
          isMaterial: false,
          sourceSheet: "A-4",
        },
        {
          description:
            "New 2x4 interior walls — upper level (closets, bath partitions per A-4)",
          quantity: 180,
          unit: "LF",
          unitPrice: 24,
          vendorCost: 16,
          isMaterial: false,
          sourceSheet: "A-4",
        },
        {
          description:
            "Box beam ceiling framing — living room, kitchen (per A-8 keynote 3.9)",
          quantity: 120,
          unit: "LF",
          unitPrice: 45,
          vendorCost: 30,
          isMaterial: false,
          sourceSheet: "A-8",
        },
        {
          description:
            "Vaulted ceiling framing modifications — T&G wood finish prep (keynote 3.8)",
          quantity: 400,
          unit: "SF",
          unitPrice: 12,
          vendorCost: 8,
          isMaterial: false,
          sourceSheet: "A-8",
        },
        {
          description:
            "Header installation — new door/window openings (bi-fold, sliding glass)",
          quantity: 6,
          unit: "EA",
          unitPrice: 850,
          vendorCost: 550,
          isMaterial: false,
          sourceSheet: "A-4",
        },
        {
          description:
            "Deck framing — new north deck, hot tub reinforcement, railing posts per A-5/A-6",
          quantity: 450,
          unit: "SF",
          unitPrice: 28,
          vendorCost: 18,
          isMaterial: false,
          sourceSheet: "A-5, A-6",
        },
        {
          description:
            "Fire-rated wall framing — 1-HR assembly (keynote 2.17)",
          quantity: 80,
          unit: "LF",
          unitPrice: 38,
          vendorCost: 26,
          isMaterial: false,
          sourceSheet: "A-7",
        },
      ],
    },

    // 4. Plumbing
    {
      trade: "plumbing",
      sectionTitle: "Plumbing",
      lineItems: [
        {
          description:
            "Rough-in plumbing — Bath 2 (new full bath, converted from WIC per A-3)",
          quantity: 1,
          unit: "LS",
          unitPrice: 8500,
          vendorCost: 6000,
          isMaterial: false,
          sourceSheet: "A-3",
        },
        {
          description:
            "Rough-in plumbing — Bath 5 (new full bath, converted from W/D per A-4)",
          quantity: 1,
          unit: "LS",
          unitPrice: 8500,
          vendorCost: 6000,
          isMaterial: false,
          sourceSheet: "A-4",
        },
        {
          description:
            "Rough-in plumbing — Master Bath remodel (freestanding tub, shower, dual vanity)",
          quantity: 1,
          unit: "LS",
          unitPrice: 12000,
          vendorCost: 8500,
          isMaterial: false,
          sourceSheet: "A-4, ID-09",
        },
        {
          description: "Rough-in plumbing — Bath 3 remodel",
          quantity: 1,
          unit: "LS",
          unitPrice: 6500,
          vendorCost: 4500,
          isMaterial: false,
          sourceSheet: "A-4",
        },
        {
          description: "Rough-in plumbing — Bath 4 remodel",
          quantity: 1,
          unit: "LS",
          unitPrice: 6500,
          vendorCost: 4500,
          isMaterial: false,
          sourceSheet: "A-4",
        },
        {
          description:
            "Rough-in plumbing — Powder Bath remodel (keynote 5.1, 5.9, 5.12)",
          quantity: 1,
          unit: "LS",
          unitPrice: 5000,
          vendorCost: 3500,
          isMaterial: false,
          sourceSheet: "A-8, ID-07",
        },
        {
          description:
            "Kitchen plumbing — main sink w/tall faucet + disposal, prep sink w/tall faucet + disposal (keynotes 5.6, 5.7)",
          quantity: 1,
          unit: "LS",
          unitPrice: 5500,
          vendorCost: 3800,
          isMaterial: false,
          sourceSheet: "A-8",
        },
        {
          description:
            "Hot tub plumbing rough-in and connection (keynote 5.14)",
          quantity: 1,
          unit: "LS",
          unitPrice: 4500,
          vendorCost: 3000,
          isMaterial: false,
          sourceSheet: "A-8",
        },
        {
          description:
            "Floor tub filler — master bath freestanding tub (keynote 5.13)",
          quantity: 1,
          unit: "EA",
          unitPrice: 1800,
          vendorCost: 1200,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description:
            'Free-standing soaking tub — master bath 71"x 30" (per ID-09)',
          quantity: 1,
          unit: "EA",
          unitPrice: 4500,
          vendorCost: 3200,
          isMaterial: true,
          sourceSheet: "ID-09",
        },
        {
          description:
            "Lavatory w/faucet — widespread faucets (6 bathrooms, keynote 5.1)",
          quantity: 8,
          unit: "EA",
          unitPrice: 950,
          vendorCost: 650,
          isMaterial: true,
          sourceSheet: "A-7, A-8",
        },
        {
          description: "Standard toilet (keynote 5.9)",
          quantity: 4,
          unit: "EA",
          unitPrice: 650,
          vendorCost: 420,
          isMaterial: true,
          sourceSheet: "A-7, A-8",
        },
        {
          description: "Corner toilet (keynote 5.12)",
          quantity: 2,
          unit: "EA",
          unitPrice: 850,
          vendorCost: 580,
          isMaterial: true,
          sourceSheet: "A-7, A-8",
        },
        {
          description:
            "Fixed shower head w/stubout @ 7'-0\" AFF (keynote 5.2)",
          quantity: 5,
          unit: "EA",
          unitPrice: 450,
          vendorCost: 280,
          isMaterial: true,
          sourceSheet: "A-7, A-8",
        },
        {
          description: "Handheld shower on slide bar (keynote 5.3)",
          quantity: 5,
          unit: "EA",
          unitPrice: 380,
          vendorCost: 240,
          isMaterial: true,
          sourceSheet: "A-7, A-8",
        },
        {
          description: "Wall mounted faucet — powder bath (keynote 5.17)",
          quantity: 1,
          unit: "EA",
          unitPrice: 650,
          vendorCost: 420,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description: "Hot + cold hose bib — exterior (keynote 5.16)",
          quantity: 2,
          unit: "EA",
          unitPrice: 350,
          vendorCost: 220,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description: "Straining water spout — bath feature (keynote 5.4)",
          quantity: 1,
          unit: "EA",
          unitPrice: 550,
          vendorCost: 350,
          isMaterial: true,
          sourceSheet: "A-8",
        },
      ],
    },

    // 5. Electrical
    {
      trade: "electrical",
      sectionTitle: "Electrical",
      lineItems: [
        {
          description:
            "Electrical rough-in — lower level full rewire per E-1 (outlets, switches, lighting layout)",
          quantity: 1,
          unit: "LS",
          unitPrice: 28000,
          vendorCost: 20000,
          isMaterial: false,
          sourceSheet: "E-1",
        },
        {
          description:
            "Electrical rough-in — upper level full rewire per E-2 (outlets, switches, lighting layout)",
          quantity: 1,
          unit: "LS",
          unitPrice: 35000,
          vendorCost: 25000,
          isMaterial: false,
          sourceSheet: "E-2",
        },
        {
          description: "Electrical panel upgrade/addition",
          quantity: 1,
          unit: "LS",
          unitPrice: 6500,
          vendorCost: 4500,
          isMaterial: false,
          sourceSheet: "E-1",
        },
        {
          description:
            '4" recessed adjustable gimbal can lights — retrofit kit 6" to 4" throughout',
          quantity: 65,
          unit: "EA",
          unitPrice: 185,
          vendorCost: 120,
          isMaterial: true,
          sourceSheet: "E-1, E-2",
        },
        {
          description:
            "Pendant chandeliers (dining, entry, bedrooms per E-2)",
          quantity: 6,
          unit: "EA",
          unitPrice: 1200,
          vendorCost: 800,
          isMaterial: true,
          sourceSheet: "E-2",
        },
        {
          description: "LED strip lighting (under cabinet, indirect)",
          quantity: 120,
          unit: "LF",
          unitPrice: 25,
          vendorCost: 15,
          isMaterial: true,
          sourceSheet: "E-1, E-2",
        },
        {
          description: "Flush linear fixtures",
          quantity: 8,
          unit: "EA",
          unitPrice: 450,
          vendorCost: 280,
          isMaterial: true,
          sourceSheet: "E-1, E-2",
        },
        {
          description: "Recessed linear fixtures",
          quantity: 6,
          unit: "EA",
          unitPrice: 550,
          vendorCost: 350,
          isMaterial: true,
          sourceSheet: "E-1, E-2",
        },
        {
          description: "Exhaust fan to outside — ultra quiet (bathrooms)",
          quantity: 6,
          unit: "EA",
          unitPrice: 380,
          vendorCost: 240,
          isMaterial: true,
          sourceSheet: "E-1, E-2",
        },
        {
          description: "Ceiling fans",
          quantity: 3,
          unit: "EA",
          unitPrice: 450,
          vendorCost: 280,
          isMaterial: true,
          sourceSheet: "E-2",
        },
        {
          description: "Sonos in-ceiling speakers (WiFi, per E-1/E-2)",
          quantity: 12,
          unit: "EA",
          unitPrice: 650,
          vendorCost: 420,
          isMaterial: true,
          sourceSheet: "E-1, E-2",
        },
        {
          description: "Security cameras — exterior",
          quantity: 4,
          unit: "EA",
          unitPrice: 850,
          vendorCost: 550,
          isMaterial: true,
          sourceSheet: "E-1, E-2",
        },
        {
          description: "Smoke/CO combo detectors — 110V interconnected",
          quantity: 10,
          unit: "EA",
          unitPrice: 185,
          vendorCost: 110,
          isMaterial: true,
          sourceSheet: "E-1, E-2",
        },
        {
          description:
            "Dark sky compliant exterior sconces (Visual Comfort Pohl or WAC Nest)",
          quantity: 12,
          unit: "EA",
          unitPrice: 650,
          vendorCost: 420,
          isMaterial: true,
          sourceSheet: "E-1, E-2",
        },
        {
          description: "Data pucks and TV jacks",
          quantity: 8,
          unit: "EA",
          unitPrice: 250,
          vendorCost: 160,
          isMaterial: true,
          sourceSheet: "E-1, E-2",
        },
        {
          description: "Doorbell and chimes",
          quantity: 1,
          unit: "EA",
          unitPrice: 450,
          vendorCost: 280,
          isMaterial: true,
          sourceSheet: "E-1",
        },
        {
          description:
            "GFCI outlets next to every toilet (per E-1/E-2 note)",
          quantity: 6,
          unit: "EA",
          unitPrice: 150,
          vendorCost: 90,
          isMaterial: true,
          sourceSheet: "E-1, E-2",
        },
      ],
    },

    // 6. HVAC
    {
      trade: "hvac",
      sectionTitle: "HVAC",
      lineItems: [
        {
          description:
            "New supply and return ductwork — wine room (per A-7 duct layout)",
          quantity: 1,
          unit: "LS",
          unitPrice: 4500,
          vendorCost: 3200,
          isMaterial: false,
          sourceSheet: "A-7",
        },
        {
          description:
            "New supply and return ductwork — flex room (per A-7 duct layout)",
          quantity: 1,
          unit: "LS",
          unitPrice: 4500,
          vendorCost: 3200,
          isMaterial: false,
          sourceSheet: "A-7",
        },
        {
          description:
            "Range hood duct — max 600 CFM to exterior (keynote 4.4)",
          quantity: 1,
          unit: "LS",
          unitPrice: 2200,
          vendorCost: 1500,
          isMaterial: false,
          sourceSheet: "A-8",
        },
        {
          description:
            "Dryer exhaust vent — existing duct to remain, verify connection",
          quantity: 1,
          unit: "LS",
          unitPrice: 800,
          vendorCost: 500,
          isMaterial: false,
          sourceSheet: "A-5",
        },
      ],
    },

    // 7. Insulation
    {
      trade: "insulation",
      sectionTitle: "Insulation",
      lineItems: [
        {
          description:
            "Ceiling insulation — R-36 or better (new areas and where disturbed)",
          quantity: 1800,
          unit: "SF",
          unitPrice: 4.5,
          vendorCost: 3,
          isMaterial: true,
          sourceSheet: "A-5",
        },
        {
          description:
            "Wall insulation — R-21 or better (new separation walls in hall & flex)",
          quantity: 1200,
          unit: "SF",
          unitPrice: 3.5,
          vendorCost: 2.25,
          isMaterial: true,
          sourceSheet: "A-5",
        },
        {
          description:
            "Exterior wall insulation — R-15 or better (existing ext walls separating hall/flex from exterior)",
          quantity: 600,
          unit: "SF",
          unitPrice: 4,
          vendorCost: 2.75,
          isMaterial: true,
          sourceSheet: "A-5",
        },
        {
          description: "Storage floor insulation — R-30 or better",
          quantity: 400,
          unit: "SF",
          unitPrice: 5.5,
          vendorCost: 3.75,
          isMaterial: true,
          sourceSheet: "A-5",
        },
      ],
    },

    // 8. Drywall & Plaster
    {
      trade: "drywall",
      sectionTitle: "Drywall & Plaster",
      lineItems: [
        {
          description:
            '5/8" GYP BD — standard walls, taped & textured, imperfect smooth and paint finish (keynote 2.1)',
          quantity: 4500,
          unit: "SF",
          unitPrice: 5.5,
          vendorCost: 3.75,
          isMaterial: false,
          sourceSheet: "A-7, A-8",
        },
        {
          description:
            '5/8" mold-resistant GYP BD — wet areas, taped & textured (keynote 2.3)',
          quantity: 1800,
          unit: "SF",
          unitPrice: 6.5,
          vendorCost: 4.5,
          isMaterial: false,
          sourceSheet: "A-7, A-8",
        },
        {
          description:
            '5/8" Fire-X drywall — 1-HR fire rated walls (keynote 3.10/2.17)',
          quantity: 600,
          unit: "SF",
          unitPrice: 7.5,
          vendorCost: 5.25,
          isMaterial: false,
          sourceSheet: "A-7",
        },
        {
          description:
            "Plaster wall finish — smooth throughout bathrooms (per ID set, powder bath, secondary bath, master bath)",
          quantity: 1200,
          unit: "SF",
          unitPrice: 12,
          vendorCost: 8,
          isMaterial: false,
          sourceSheet: "ID-07, ID-09, ID-12",
        },
        {
          description:
            '5/8" GYP BD ceiling — standard (keynote 3.1)',
          quantity: 3200,
          unit: "SF",
          unitPrice: 6,
          vendorCost: 4,
          isMaterial: false,
          sourceSheet: "A-7, A-8",
        },
        {
          description:
            '5/8" mold-resistant GYP BD ceiling — wet areas (keynote 3.3)',
          quantity: 600,
          unit: "SF",
          unitPrice: 7,
          vendorCost: 4.75,
          isMaterial: false,
          sourceSheet: "A-7, A-8",
        },
      ],
    },

    // 9. Tile & Stone
    {
      trade: "masonry",
      sectionTitle: "Tile & Stone",
      lineItems: [
        {
          description:
            "All-stone fireplace — living room full surround (per ID-05.1, keynote 2.10)",
          quantity: 1,
          unit: "LS",
          unitPrice: 28000,
          vendorCost: 18000,
          isMaterial: false,
          sourceSheet: "ID-05.1",
        },
        {
          description: "Flagstone flooring — secondary bathroom (per ID-12)",
          quantity: 65,
          unit: "SF",
          unitPrice: 35,
          vendorCost: 22,
          isMaterial: true,
          sourceSheet: "ID-12",
        },
        {
          description:
            'Limestone flooring — powder bath, 1/4" x 3/4" (per ID-07)',
          quantity: 45,
          unit: "SF",
          unitPrice: 42,
          vendorCost: 28,
          isMaterial: true,
          sourceSheet: "ID-07",
        },
        {
          description:
            "Shower tile — subway tile, upper guest bath (per ID-14)",
          quantity: 120,
          unit: "SF",
          unitPrice: 28,
          vendorCost: 18,
          isMaterial: false,
          sourceSheet: "ID-14",
        },
        {
          description:
            "Shower tile — flagstone/stone, master bath (per ID-09)",
          quantity: 140,
          unit: "SF",
          unitPrice: 38,
          vendorCost: 24,
          isMaterial: false,
          sourceSheet: "ID-09",
        },
        {
          description:
            "Shower tile — stone clad, secondary bath (per ID-12)",
          quantity: 100,
          unit: "SF",
          unitPrice: 38,
          vendorCost: 24,
          isMaterial: false,
          sourceSheet: "ID-12",
        },
        {
          description:
            "Shower curb — 3\" stone clad (secondary bath per ID-12)",
          quantity: 6,
          unit: "LF",
          unitPrice: 85,
          vendorCost: 55,
          isMaterial: false,
          sourceSheet: "ID-12",
        },
        {
          description:
            "Kitchen backsplash tile — per ID-06.1 elevations",
          quantity: 60,
          unit: "SF",
          unitPrice: 32,
          vendorCost: 20,
          isMaterial: false,
          sourceSheet: "ID-06.1",
        },
        {
          description: "Countertop stone — master bath vanity (per ID-09)",
          quantity: 30,
          unit: "SF",
          unitPrice: 95,
          vendorCost: 65,
          isMaterial: true,
          sourceSheet: "ID-09",
        },
        {
          description:
            "Countertop stone — secondary bath floating vanity (per ID-12)",
          quantity: 15,
          unit: "SF",
          unitPrice: 95,
          vendorCost: 65,
          isMaterial: true,
          sourceSheet: "ID-12",
        },
        {
          description:
            "Stone slab — safety stone 16.5\" H in front of hearth, living room (per ID-05.1)",
          quantity: 1,
          unit: "LS",
          unitPrice: 3500,
          vendorCost: 2200,
          isMaterial: true,
          sourceSheet: "ID-05.1",
        },
      ],
    },

    // 10. Finish Carpentry & Casework
    {
      trade: "carpentry",
      sectionTitle: "Finish Carpentry & Casework",
      lineItems: [
        {
          description:
            "Kitchen cabinets — full custom per ID-06, ID-06.1, ID-06.2 (uppers, lowers, island, pantry, coffee station)",
          quantity: 1,
          unit: "LS",
          unitPrice: 65000,
          vendorCost: 45000,
          isMaterial: true,
          sourceSheet: "ID-06, ID-06.1, ID-06.2",
        },
        {
          description:
            "Kitchen island — custom with reclaimed wood cabinet style (per ID-06.2)",
          quantity: 1,
          unit: "LS",
          unitPrice: 18000,
          vendorCost: 12000,
          isMaterial: true,
          sourceSheet: "ID-06.2",
        },
        {
          description:
            '1.5" quartzite countertops — kitchen, undermount sink cutouts (per ID-06.1)',
          quantity: 65,
          unit: "SF",
          unitPrice: 125,
          vendorCost: 85,
          isMaterial: true,
          sourceSheet: "ID-06.1",
        },
        {
          description:
            "Custom built-in cabinets — living room flanking fireplace (per ID-05)",
          quantity: 2,
          unit: "EA",
          unitPrice: 6500,
          vendorCost: 4500,
          isMaterial: true,
          sourceSheet: "ID-05",
        },
        {
          description: "Built-in window seats — living room (per ID-05)",
          quantity: 2,
          unit: "EA",
          unitPrice: 4500,
          vendorCost: 3000,
          isMaterial: true,
          sourceSheet: "ID-05",
        },
        {
          description:
            "Custom built-in WIC closet cabinets — full height (per A-4, keynote 6.3, 6.8)",
          quantity: 1,
          unit: "LS",
          unitPrice: 15000,
          vendorCost: 10000,
          isMaterial: true,
          sourceSheet: "A-4",
        },
        {
          description:
            "Secondary closet — full-height cabinetry wall w/fabric-backed glass doors (per ID-11)",
          quantity: 1,
          unit: "LS",
          unitPrice: 12000,
          vendorCost: 8000,
          isMaterial: true,
          sourceSheet: "ID-11",
        },
        {
          description:
            "Banquette booth — dining/nook area (keynote 6.21)",
          quantity: 1,
          unit: "EA",
          unitPrice: 5500,
          vendorCost: 3800,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description:
            "Custom bar/wet bar — per kitchen area (keynote 6.7)",
          quantity: 1,
          unit: "LS",
          unitPrice: 8500,
          vendorCost: 5800,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description:
            "Window seat — 32\" tall x 4' each, drawers below (keynote 6.19)",
          quantity: 3,
          unit: "EA",
          unitPrice: 3500,
          vendorCost: 2400,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description:
            "Theater/den cabinets — built-in media console (per ID-16)",
          quantity: 1,
          unit: "LS",
          unitPrice: 6000,
          vendorCost: 4000,
          isMaterial: true,
          sourceSheet: "ID-16",
        },
        {
          description:
            "Laundry room cabinets — existing to remain, replace countertop/backsplash material (per ID-15)",
          quantity: 1,
          unit: "LS",
          unitPrice: 3500,
          vendorCost: 2400,
          isMaterial: true,
          sourceSheet: "ID-15",
        },
        {
          description:
            "Bathroom vanity cabinets — 56\" custom vanity, floating wall vanity, etc. (6 baths per ID set)",
          quantity: 6,
          unit: "EA",
          unitPrice: 4500,
          vendorCost: 3000,
          isMaterial: true,
          sourceSheet: "ID-07 through ID-14",
        },
        {
          description:
            "Recessed medicine cabinets — bathrooms (per ID-12)",
          quantity: 3,
          unit: "EA",
          unitPrice: 850,
          vendorCost: 550,
          isMaterial: true,
          sourceSheet: "ID-12",
        },
        {
          description: "Shoe rack — entry/closet (keynote 6.5)",
          quantity: 2,
          unit: "EA",
          unitPrice: 1800,
          vendorCost: 1200,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description:
            "Custom upholstered headboard/pony wall — secondary bedroom (per ID-10)",
          quantity: 1,
          unit: "EA",
          unitPrice: 4500,
          vendorCost: 3000,
          isMaterial: true,
          sourceSheet: "ID-10",
        },
        {
          description:
            "24\" deep closet cabinet w/show drawers — bedrooms (keynote 6.24)",
          quantity: 2,
          unit: "EA",
          unitPrice: 3200,
          vendorCost: 2200,
          isMaterial: true,
          sourceSheet: "A-8",
        },
      ],
    },

    // 11. Painting & Staining
    {
      trade: "painting",
      sectionTitle: "Painting & Staining",
      lineItems: [
        {
          description:
            "Interior paint — walls, imperfect smooth finish throughout remodeled areas",
          quantity: 8500,
          unit: "SF",
          unitPrice: 3.5,
          vendorCost: 2.25,
          isMaterial: false,
          sourceSheet: "A-7, A-8",
        },
        {
          description: "Interior paint — ceilings, smooth finish",
          quantity: 3800,
          unit: "SF",
          unitPrice: 3,
          vendorCost: 2,
          isMaterial: false,
          sourceSheet: "A-7, A-8",
        },
        {
          description:
            "Paint grade T&G wall finish — upper guest bedroom (per ID-13, keynote 2.1 variant)",
          quantity: 350,
          unit: "SF",
          unitPrice: 6,
          vendorCost: 4,
          isMaterial: false,
          sourceSheet: "ID-13",
        },
        {
          description:
            "Exterior re-stain — existing siding to remain and be re-stained (per A-5 notes)",
          quantity: 1,
          unit: "LS",
          unitPrice: 18000,
          vendorCost: 12000,
          isMaterial: false,
          sourceSheet: "A-5",
        },
        {
          description:
            "Interior door and trim painting — all new doors and casings",
          quantity: 30,
          unit: "EA",
          unitPrice: 250,
          vendorCost: 165,
          isMaterial: false,
          sourceSheet: "A-3, A-4",
        },
      ],
    },

    // 12. Flooring
    {
      trade: "flooring",
      sectionTitle: "Flooring",
      lineItems: [
        {
          description:
            "Wood flooring — install throughout main living areas (keynote 1.2)",
          quantity: 1800,
          unit: "SF",
          unitPrice: 16,
          vendorCost: 10,
          isMaterial: true,
          sourceSheet: "A-7, A-8",
        },
        {
          description:
            "Tile flooring — bathrooms, entry, laundry (keynote 1.3)",
          quantity: 450,
          unit: "SF",
          unitPrice: 22,
          vendorCost: 14,
          isMaterial: true,
          sourceSheet: "A-7, A-8",
        },
        {
          description:
            "Carpet — bedrooms, theater/den (keynote 1.4)",
          quantity: 600,
          unit: "SF",
          unitPrice: 12,
          vendorCost: 8,
          isMaterial: true,
          sourceSheet: "A-7, A-8",
        },
        {
          description:
            "Waterproof plank flooring — upper guest bathroom (per ID-14)",
          quantity: 55,
          unit: "SF",
          unitPrice: 14,
          vendorCost: 9,
          isMaterial: true,
          sourceSheet: "ID-14",
        },
        {
          description:
            "Grate flooring — at deck drip line (keynote 1.13)",
          quantity: 30,
          unit: "SF",
          unitPrice: 45,
          vendorCost: 30,
          isMaterial: true,
          sourceSheet: "A-8",
        },
      ],
    },

    // 13. Specialty — Reclaimed Wood
    {
      trade: "carpentry",
      sectionTitle: "Specialty — Reclaimed Wood",
      lineItems: [
        {
          description:
            "Reclaimed wood wall cladding — primary bedroom, all walls and ceiling (per ID-08)",
          quantity: 850,
          unit: "SF",
          unitPrice: 28,
          vendorCost: 18,
          isMaterial: true,
          sourceSheet: "ID-08",
        },
        {
          description:
            "Reclaimed wood panel wall — dining room accent (keynote 2.15, per ID-04)",
          quantity: 180,
          unit: "SF",
          unitPrice: 28,
          vendorCost: 18,
          isMaterial: true,
          sourceSheet: "ID-04",
        },
        {
          description:
            "Reclaimed wood cabinet style — kitchen island face (per ID-06.2)",
          quantity: 40,
          unit: "SF",
          unitPrice: 35,
          vendorCost: 22,
          isMaterial: true,
          sourceSheet: "ID-06.2",
        },
        {
          description:
            "Reclaimed wood square island posts — kitchen (per ID-06.2 details)",
          quantity: 4,
          unit: "EA",
          unitPrice: 650,
          vendorCost: 420,
          isMaterial: true,
          sourceSheet: "ID-06.2",
        },
        {
          description:
            "8\" x 8\" faux beam wraps — reclaimed wood (kitchen, living room per ID-06.1)",
          quantity: 80,
          unit: "LF",
          unitPrice: 55,
          vendorCost: 35,
          isMaterial: true,
          sourceSheet: "ID-06.1",
        },
      ],
    },

    // 14. Specialty — Custom Metalwork
    {
      trade: "welding",
      sectionTitle: "Specialty — Custom Metalwork",
      lineItems: [
        {
          description:
            "Custom iron/steel shower door enclosure — master bath (per ID-09)",
          quantity: 1,
          unit: "EA",
          unitPrice: 8500,
          vendorCost: 5500,
          isMaterial: true,
          sourceSheet: "ID-09",
        },
        {
          description:
            "Bypass frameless glass shower doors — secondary bath (per ID-12)",
          quantity: 1,
          unit: "EA",
          unitPrice: 4500,
          vendorCost: 3000,
          isMaterial: true,
          sourceSheet: "ID-12",
        },
        {
          description:
            "Deck railing — 1/2\"x1\" or 1/4\"x1/4\" vertical circular/square metal balusters @ 4\" O.C. max (per A-6 detail)",
          quantity: 120,
          unit: "LF",
          unitPrice: 95,
          vendorCost: 65,
          isMaterial: true,
          sourceSheet: "A-6",
        },
        {
          description: "Glass shower wall — per keynote 2.13",
          quantity: 2,
          unit: "EA",
          unitPrice: 3500,
          vendorCost: 2200,
          isMaterial: true,
          sourceSheet: "A-7, A-8",
        },
      ],
    },

    // 15. Decking & Exterior
    {
      trade: "carpentry",
      sectionTitle: "Decking & Exterior",
      lineItems: [
        {
          description:
            "TimberTech/advanced PVC decking — new north deck and expanded rear deck (keynote 1.8)",
          quantity: 550,
          unit: "SF",
          unitPrice: 32,
          vendorCost: 20,
          isMaterial: true,
          sourceSheet: "A-4, A-5, A-6",
        },
        {
          description:
            "Hot tub — supply and install on reinforced deck pad (keynote 5.14)",
          quantity: 1,
          unit: "EA",
          unitPrice: 15000,
          vendorCost: 10000,
          isMaterial: true,
          sourceSheet: "A-4",
        },
        {
          description:
            "Gas firepit table — deck mounted (keynote 7.7)",
          quantity: 1,
          unit: "EA",
          unitPrice: 4500,
          vendorCost: 3000,
          isMaterial: true,
          sourceSheet: "A-4, A-8",
        },
        {
          description:
            "3x3 guardrail posts @ 5' O.C. max, per engineering (per A-6 detail)",
          quantity: 24,
          unit: "EA",
          unitPrice: 185,
          vendorCost: 120,
          isMaterial: true,
          sourceSheet: "A-6",
        },
        {
          description:
            '1-1/2"x3-1/2" or 5-1/2" wood top rail w/1/2"x1" bottom rail',
          quantity: 120,
          unit: "LF",
          unitPrice: 28,
          vendorCost: 18,
          isMaterial: true,
          sourceSheet: "A-6",
        },
        {
          description:
            "Exterior stairs — new deck access (per A-4, A-6)",
          quantity: 2,
          unit: "EA",
          unitPrice: 3500,
          vendorCost: 2200,
          isMaterial: false,
          sourceSheet: "A-4, A-6",
        },
      ],
    },

    // 16. Windows & Doors
    {
      trade: "glazing",
      sectionTitle: "Windows & Doors",
      lineItems: [
        {
          description:
            "Bi-fold door — 12' wide (mark 201 per A-4 door schedule)",
          quantity: 1,
          unit: "EA",
          unitPrice: 12000,
          vendorCost: 8000,
          isMaterial: true,
          sourceSheet: "A-4",
        },
        {
          description:
            "Single full glass wood door — 2'x6'8\" privacy glass (mark 202)",
          quantity: 1,
          unit: "EA",
          unitPrice: 2200,
          vendorCost: 1500,
          isMaterial: true,
          sourceSheet: "A-4",
        },
        {
          description:
            "Single flush wood doors — 2'x6'8\" (mark 203, multiple)",
          quantity: 6,
          unit: "EA",
          unitPrice: 950,
          vendorCost: 650,
          isMaterial: true,
          sourceSheet: "A-4",
        },
        {
          description:
            "Single flush wood door — 2'-10\" x 6'8\" (mark 204)",
          quantity: 2,
          unit: "EA",
          unitPrice: 1100,
          vendorCost: 750,
          isMaterial: true,
          sourceSheet: "A-4",
        },
        {
          description:
            "Double sliding glass door — 7'x7' (mark 205)",
          quantity: 1,
          unit: "EA",
          unitPrice: 5500,
          vendorCost: 3800,
          isMaterial: true,
          sourceSheet: "A-4",
        },
        {
          description:
            "Pocket 2-panel wood door — 2'x6'8\" (mark 206)",
          quantity: 2,
          unit: "EA",
          unitPrice: 1400,
          vendorCost: 950,
          isMaterial: true,
          sourceSheet: "A-4",
        },
        {
          description:
            "Single 6-panel wood door — relocated (mark 207)",
          quantity: 1,
          unit: "EA",
          unitPrice: 850,
          vendorCost: 580,
          isMaterial: true,
          sourceSheet: "A-4",
        },
        {
          description:
            "Trapezoid window — 84\" x 43-1/4\" (mark 200, safety glazing)",
          quantity: 2,
          unit: "EA",
          unitPrice: 4500,
          vendorCost: 3000,
          isMaterial: true,
          sourceSheet: "A-4",
        },
        {
          description:
            "Casement single right window — 84\" x 44\" (mark 201 window)",
          quantity: 2,
          unit: "EA",
          unitPrice: 2800,
          vendorCost: 1900,
          isMaterial: true,
          sourceSheet: "A-4",
        },
        {
          description:
            "Fixed window — 90\" x 80\" (mark 202 window, 11'-2\" head)",
          quantity: 2,
          unit: "EA",
          unitPrice: 3800,
          vendorCost: 2600,
          isMaterial: true,
          sourceSheet: "A-4",
        },
        {
          description:
            "Lower level — single 6-panel wood doors (marks 100-103, mix of relocated and new)",
          quantity: 5,
          unit: "EA",
          unitPrice: 950,
          vendorCost: 650,
          isMaterial: true,
          sourceSheet: "A-3",
        },
        {
          description:
            "Lower level — single door privacy glass (mark 104)",
          quantity: 1,
          unit: "EA",
          unitPrice: 1400,
          vendorCost: 950,
          isMaterial: true,
          sourceSheet: "A-3",
        },
        {
          description:
            "Lower level — casement window (mark 101, 38\" x 54\", 7'-6\" head)",
          quantity: 1,
          unit: "EA",
          unitPrice: 1800,
          vendorCost: 1200,
          isMaterial: true,
          sourceSheet: "A-3",
        },
        {
          description:
            "Door and window trim — A07 detail, all new openings",
          quantity: 40,
          unit: "EA",
          unitPrice: 350,
          vendorCost: 220,
          isMaterial: true,
          sourceSheet: "A-6",
        },
      ],
    },

    // 17. Appliances & Fixtures
    {
      trade: "general_labor",
      sectionTitle: "Appliances & Fixtures",
      lineItems: [
        {
          description:
            "48\" range — max 600 CFM (keynote 4.4)",
          quantity: 1,
          unit: "EA",
          unitPrice: 8500,
          vendorCost: 6500,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description:
            "Range hood — max 600 CFM, not to exceed (keynote 4.3)",
          quantity: 1,
          unit: "EA",
          unitPrice: 2200,
          vendorCost: 1500,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description: "Dishwasher (keynote 4.5)",
          quantity: 1,
          unit: "EA",
          unitPrice: 1200,
          vendorCost: 850,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description: "Under-counter refrigerator (keynote 4.8)",
          quantity: 1,
          unit: "EA",
          unitPrice: 1800,
          vendorCost: 1200,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description:
            "Panel-ready refrigerator — full size (per A-4 kitchen layout)",
          quantity: 1,
          unit: "EA",
          unitPrice: 5500,
          vendorCost: 4200,
          isMaterial: true,
          sourceSheet: "A-4",
        },
        {
          description:
            "Two front load washer/dryer set (keynote 4.9)",
          quantity: 1,
          unit: "EA",
          unitPrice: 3500,
          vendorCost: 2500,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description: "Ice maker (keynote 4.15)",
          quantity: 1,
          unit: "EA",
          unitPrice: 2200,
          vendorCost: 1500,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description:
            "TRPA-approved gas fireplace — living room (keynote 4.1)",
          quantity: 1,
          unit: "EA",
          unitPrice: 6500,
          vendorCost: 4500,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description:
            "Vent — bathroom and kitchen exhaust (keynote 4.7)",
          quantity: 7,
          unit: "EA",
          unitPrice: 250,
          vendorCost: 160,
          isMaterial: true,
          sourceSheet: "A-7, A-8",
        },
        {
          description:
            "Towel bars, hooks, robe hooks — all bathrooms (keynotes 7.1, 7.2)",
          quantity: 18,
          unit: "EA",
          unitPrice: 120,
          vendorCost: 75,
          isMaterial: true,
          sourceSheet: "A-7, A-8",
        },
        {
          description: "Mirrors — bathrooms (keynote 7.11)",
          quantity: 6,
          unit: "EA",
          unitPrice: 650,
          vendorCost: 420,
          isMaterial: true,
          sourceSheet: "A-7, A-8",
        },
        {
          description:
            "Frosted glass panel — bath partition (keynote 7.9)",
          quantity: 2,
          unit: "EA",
          unitPrice: 1200,
          vendorCost: 800,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description:
            "TV on exterior arm — deck/outdoor (keynote 7.25)",
          quantity: 1,
          unit: "EA",
          unitPrice: 850,
          vendorCost: 550,
          isMaterial: true,
          sourceSheet: "A-8",
        },
        {
          description: "Projector screen — theater/den (per ID-16)",
          quantity: 1,
          unit: "EA",
          unitPrice: 2500,
          vendorCost: 1800,
          isMaterial: true,
          sourceSheet: "ID-16",
        },
      ],
    },

    // 18. Site Work & TRPA Compliance
    {
      trade: "excavation",
      sectionTitle: "Site Work & TRPA Compliance",
      lineItems: [
        {
          description:
            "Site grading — proposed per SP-1 (cut 4 CY, fill 1 CY, cross cut/fill 3 CY)",
          quantity: 1,
          unit: "LS",
          unitPrice: 8500,
          vendorCost: 6000,
          isMaterial: false,
          sourceSheet: "SP-1",
        },
        {
          description:
            "Temporary boundary construction fencing (BMP 501)",
          quantity: 300,
          unit: "LF",
          unitPrice: 12,
          vendorCost: 8,
          isMaterial: true,
          sourceSheet: "SP-4.1",
        },
        {
          description: "Vegetation protection fencing (BMP 507)",
          quantity: 200,
          unit: "LF",
          unitPrice: 8,
          vendorCost: 5,
          isMaterial: true,
          sourceSheet: "SP-4.1",
        },
        {
          description: "Silt fence installation (BMP 513)",
          quantity: 250,
          unit: "LF",
          unitPrice: 10,
          vendorCost: 6,
          isMaterial: true,
          sourceSheet: "SP-4.1",
        },
        {
          description:
            "Silt fence placement at erosion control points (BMP 516)",
          quantity: 150,
          unit: "LF",
          unitPrice: 10,
          vendorCost: 6,
          isMaterial: true,
          sourceSheet: "SP-4.1",
        },
        {
          description: "Sediment trap installation — small (BMP 030)",
          quantity: 2,
          unit: "EA",
          unitPrice: 1800,
          vendorCost: 1200,
          isMaterial: false,
          sourceSheet: "SP-4.1",
        },
        {
          description: "Parking barriers installation (BMP 026)",
          quantity: 6,
          unit: "EA",
          unitPrice: 250,
          vendorCost: 160,
          isMaterial: true,
          sourceSheet: "SP-4.1",
        },
        {
          description: "Drip line conveyance swale (BMP 004)",
          quantity: 80,
          unit: "LF",
          unitPrice: 18,
          vendorCost: 12,
          isMaterial: false,
          sourceSheet: "SP-4.1",
        },
        {
          description:
            "Defensible space clearing — Zones 1-3 per SP-3 (tree trimming, brush removal, pine needle removal)",
          quantity: 1,
          unit: "LS",
          unitPrice: 12000,
          vendorCost: 8000,
          isMaterial: false,
          sourceSheet: "SP-3",
        },
        {
          description:
            "Erosion control for elevated structures (BMP 010) — drain rock under decks",
          quantity: 10,
          unit: "CY",
          unitPrice: 185,
          vendorCost: 120,
          isMaterial: true,
          sourceSheet: "SP-4.1",
        },
        {
          description:
            "Revegetation — disturbed areas per TRPA BMP handbook",
          quantity: 1,
          unit: "LS",
          unitPrice: 5000,
          vendorCost: 3500,
          isMaterial: false,
          sourceSheet: "SP-2",
        },
        {
          description:
            "Mulch — 2-3\" layer over all disturbed areas during construction",
          quantity: 15,
          unit: "CY",
          unitPrice: 95,
          vendorCost: 60,
          isMaterial: true,
          sourceSheet: "SP-4",
        },
      ],
    },
  ],

  tasks: [
    // Phase: Pre-Construction
    {
      name: "Permits & TRPA approvals",
      trade: "general_labor",
      phase: "Pre-Construction",
      durationDays: 14,
      dependsOn: [],
      isCriticalPath: true,
      isMilestoneTask: true,
    },
    {
      name: "Long-lead material procurement (windows, custom metal, reclaimed wood)",
      trade: "general_labor",
      phase: "Pre-Construction",
      durationDays: 30,
      dependsOn: [],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Sub contracts finalized",
      trade: "general_labor",
      phase: "Pre-Construction",
      durationDays: 7,
      dependsOn: ["Permits & TRPA approvals"],
      isCriticalPath: true,
      isMilestoneTask: false,
    },

    // Phase: Demolition
    {
      name: "Site preparation & BMP installation",
      trade: "excavation",
      phase: "Demolition",
      durationDays: 3,
      dependsOn: ["Sub contracts finalized"],
      isCriticalPath: true,
      isMilestoneTask: false,
    },
    {
      name: "Interior demolition — upper level",
      trade: "demolition",
      phase: "Demolition",
      durationDays: 5,
      dependsOn: ["Site preparation & BMP installation"],
      isCriticalPath: true,
      isMilestoneTask: false,
    },
    {
      name: "Interior demolition — lower level",
      trade: "demolition",
      phase: "Demolition",
      durationDays: 4,
      dependsOn: ["Site preparation & BMP installation"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Deck demolition",
      trade: "demolition",
      phase: "Demolition",
      durationDays: 2,
      dependsOn: ["Site preparation & BMP installation"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Debris haul-off",
      trade: "demolition",
      phase: "Demolition",
      durationDays: 2,
      dependsOn: [
        "Interior demolition — upper level",
        "Interior demolition — lower level",
        "Deck demolition",
      ],
      isCriticalPath: true,
      isMilestoneTask: true,
    },

    // Phase: Structural
    {
      name: "Foundation work — flex room slab & stem walls",
      trade: "concrete",
      phase: "Structural",
      durationDays: 10,
      dependsOn: ["Debris haul-off"],
      isCriticalPath: true,
      isMilestoneTask: false,
    },
    {
      name: "Framing — lower level walls",
      trade: "carpentry",
      phase: "Structural",
      durationDays: 5,
      dependsOn: ["Foundation work — flex room slab & stem walls"],
      isCriticalPath: true,
      isMilestoneTask: false,
    },
    {
      name: "Framing — upper level walls & ceiling mods",
      trade: "carpentry",
      phase: "Structural",
      durationDays: 8,
      dependsOn: ["Debris haul-off"],
      isCriticalPath: true,
      isMilestoneTask: false,
    },
    {
      name: "Framing — deck structure",
      trade: "carpentry",
      phase: "Structural",
      durationDays: 5,
      dependsOn: ["Debris haul-off"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },

    // Phase: Rough-In
    {
      name: "Rough plumbing — all bathrooms and kitchen",
      trade: "plumbing",
      phase: "Rough-In",
      durationDays: 12,
      dependsOn: [
        "Framing — lower level walls",
        "Framing — upper level walls & ceiling mods",
      ],
      isCriticalPath: true,
      isMilestoneTask: false,
    },
    {
      name: "Rough electrical — full rewire both levels",
      trade: "electrical",
      phase: "Rough-In",
      durationDays: 14,
      dependsOn: [
        "Framing — lower level walls",
        "Framing — upper level walls & ceiling mods",
      ],
      isCriticalPath: true,
      isMilestoneTask: false,
    },
    {
      name: "HVAC ductwork — wine room & flex room",
      trade: "hvac",
      phase: "Rough-In",
      durationDays: 3,
      dependsOn: ["Framing — lower level walls"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Rough-in inspections (plumbing, electrical, framing)",
      trade: "general_labor",
      phase: "Rough-In",
      durationDays: 3,
      dependsOn: [
        "Rough plumbing — all bathrooms and kitchen",
        "Rough electrical — full rewire both levels",
      ],
      isCriticalPath: true,
      isMilestoneTask: true,
    },

    // Phase: Close-In
    {
      name: "Insulation — all zones",
      trade: "insulation",
      phase: "Close-In",
      durationDays: 5,
      dependsOn: ["Rough-in inspections (plumbing, electrical, framing)"],
      isCriticalPath: true,
      isMilestoneTask: false,
    },
    {
      name: "Window & door installation",
      trade: "glazing",
      phase: "Close-In",
      durationDays: 5,
      dependsOn: ["Framing — upper level walls & ceiling mods"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Drywall hang & tape",
      trade: "drywall",
      phase: "Close-In",
      durationDays: 12,
      dependsOn: ["Insulation — all zones"],
      isCriticalPath: true,
      isMilestoneTask: false,
    },
    {
      name: "Plaster wall finish — bathrooms",
      trade: "drywall",
      phase: "Close-In",
      durationDays: 5,
      dependsOn: ["Drywall hang & tape"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },

    // Phase: Finish
    {
      name: "Interior paint — walls & ceilings",
      trade: "painting",
      phase: "Finish",
      durationDays: 10,
      dependsOn: ["Drywall hang & tape"],
      isCriticalPath: true,
      isMilestoneTask: false,
    },
    {
      name: "Tile & stone installation — all bathrooms",
      trade: "masonry",
      phase: "Finish",
      durationDays: 14,
      dependsOn: ["Drywall hang & tape"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Stone fireplace installation",
      trade: "masonry",
      phase: "Finish",
      durationDays: 8,
      dependsOn: ["Drywall hang & tape"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Flooring installation — wood, tile, carpet",
      trade: "flooring",
      phase: "Finish",
      durationDays: 10,
      dependsOn: ["Interior paint — walls & ceilings"],
      isCriticalPath: true,
      isMilestoneTask: false,
    },
    {
      name: "Casework & cabinet installation — kitchen",
      trade: "carpentry",
      phase: "Finish",
      durationDays: 8,
      dependsOn: ["Interior paint — walls & ceilings"],
      isCriticalPath: true,
      isMilestoneTask: false,
    },
    {
      name: "Casework installation — all other rooms",
      trade: "carpentry",
      phase: "Finish",
      durationDays: 10,
      dependsOn: ["Interior paint — walls & ceilings"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Reclaimed wood cladding — primary suite, kitchen, living",
      trade: "carpentry",
      phase: "Finish",
      durationDays: 10,
      dependsOn: ["Interior paint — walls & ceilings"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Custom metalwork — shower doors, railings",
      trade: "welding",
      phase: "Finish",
      durationDays: 5,
      dependsOn: ["Tile & stone installation — all bathrooms"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Electrical trim — fixtures, switches, devices",
      trade: "electrical",
      phase: "Finish",
      durationDays: 8,
      dependsOn: ["Interior paint — walls & ceilings"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Plumbing trim — fixtures, faucets, connections",
      trade: "plumbing",
      phase: "Finish",
      durationDays: 6,
      dependsOn: [
        "Tile & stone installation — all bathrooms",
        "Casework & cabinet installation — kitchen",
      ],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Countertop installation — kitchen & bathrooms",
      trade: "masonry",
      phase: "Finish",
      durationDays: 3,
      dependsOn: [
        "Casework & cabinet installation — kitchen",
        "Casework installation — all other rooms",
      ],
      isCriticalPath: true,
      isMilestoneTask: false,
    },

    // Phase: Exterior
    {
      name: "Decking installation — TimberTech",
      trade: "carpentry",
      phase: "Exterior",
      durationDays: 8,
      dependsOn: ["Framing — deck structure"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Hot tub installation",
      trade: "plumbing",
      phase: "Exterior",
      durationDays: 3,
      dependsOn: ["Decking installation — TimberTech"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Gas firepit installation",
      trade: "plumbing",
      phase: "Exterior",
      durationDays: 1,
      dependsOn: ["Decking installation — TimberTech"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Railing installation — metal balusters",
      trade: "welding",
      phase: "Exterior",
      durationDays: 4,
      dependsOn: ["Decking installation — TimberTech"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Exterior re-stain",
      trade: "painting",
      phase: "Exterior",
      durationDays: 5,
      dependsOn: ["Window & door installation"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Defensible space clearing",
      trade: "excavation",
      phase: "Exterior",
      durationDays: 5,
      dependsOn: ["Site preparation & BMP installation"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },
    {
      name: "Site work — revegetation & final BMPs",
      trade: "excavation",
      phase: "Exterior",
      durationDays: 3,
      dependsOn: ["Defensible space clearing"],
      isCriticalPath: false,
      isMilestoneTask: false,
    },

    // Phase: Punch & Close
    {
      name: "Appliance installation & commissioning",
      trade: "general_labor",
      phase: "Punch & Close",
      durationDays: 3,
      dependsOn: [
        "Countertop installation — kitchen & bathrooms",
        "Plumbing trim — fixtures, faucets, connections",
        "Electrical trim — fixtures, switches, devices",
      ],
      isCriticalPath: true,
      isMilestoneTask: false,
    },
    {
      name: "Punch list walkthrough",
      trade: "general_labor",
      phase: "Punch & Close",
      durationDays: 3,
      dependsOn: [
        "Appliance installation & commissioning",
        "Flooring installation — wood, tile, carpet",
        "Reclaimed wood cladding — primary suite, kitchen, living",
      ],
      isCriticalPath: true,
      isMilestoneTask: false,
    },
    {
      name: "Punch list corrections",
      trade: "general_labor",
      phase: "Punch & Close",
      durationDays: 5,
      dependsOn: ["Punch list walkthrough"],
      isCriticalPath: true,
      isMilestoneTask: false,
    },
    {
      name: "Final inspections — building, electrical, plumbing, TRPA",
      trade: "general_labor",
      phase: "Punch & Close",
      durationDays: 5,
      dependsOn: ["Punch list corrections"],
      isCriticalPath: true,
      isMilestoneTask: true,
    },
    {
      name: "Client walkthrough & handover",
      trade: "general_labor",
      phase: "Punch & Close",
      durationDays: 1,
      dependsOn: ["Final inspections — building, electrical, plumbing, TRPA"],
      isCriticalPath: true,
      isMilestoneTask: true,
    },
  ],

  milestones: [
    {
      name: "Contract Signed",
      position: 1,
      billingPercentage: 10,
    },
    {
      name: "Demolition Complete",
      position: 2,
      billingPercentage: 10,
    },
    {
      name: "Rough-In Inspections Passed",
      position: 3,
      billingPercentage: 20,
    },
    {
      name: "Drywall & Close-In Complete",
      position: 4,
      billingPercentage: 15,
    },
    {
      name: "Finish Phase 50% Complete",
      position: 5,
      billingPercentage: 15,
    },
    {
      name: "Substantial Completion",
      position: 6,
      billingPercentage: 20,
    },
    {
      name: "Final Inspection & Handover",
      position: 7,
      billingPercentage: 10,
    },
  ],
};
